name: tasker
description: "manager your daily work"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.0-323.2.beta
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  intl: ^0.17.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.0
  analyzer: 4.7.0
  flutter_lints: ^5.0.0
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # see https://flutter.dev/to/font-from-package
analyzer:
  enable-experiment:
    - records