name: weather
description: "manager your daily work"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.1.0
  google_fonts: ^4.0.3
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.0
  analyzer: 4.7.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/weather/partly-cloudy-night-rain.svg
    - assets/weather/overcast-night-rain.svg
    - assets/weather/rain.svg
  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300

analyzer:
  enable-experiment:
    - records

# flutter_native_splash:
#   color: "#232730"
#   image: assets/splash/splash_icon.png
#   android: true
#   ios: true

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/app_icon.png"